### ISSUE TITLE
请问下。我直接下载。放到拓展包里。直接报错了

### ISSUE THREAD

**Issue by cyq33** [minzhi3/playable-build-tool#3]

**Comment by cyq33** [comment]
![image](https://user-images.githubusercontent.com/86040766/192073973-32c2bdc7-2ac9-40a2-84e5-b94212d1cff5.png)

**Comment by minzhi3** [comment]
下载的源代码需要node命令编译

不熟悉命令可以下releases编译好的包

https://github.com/minzhi3/playable-build-tool/releases

**Comment by cyq33** [comment]
> 

感谢感谢。 
![image](https://user-images.githubusercontent.com/86040766/192176945-1c32faf4-e76e-409e-9097-68864b478a19.png)
直接执行这个编译吗？

**Comment by minzhi3** [comment]
嗯对的

**Comment by cyq33** [comment]
好勒。感谢
